### ISSUE TITLE
The method 'toDouble' was called on null.

### ISSUE THREAD

**Issue by cuongpxu** [marcglasberg/image_pixels#2]
Hi, 

I got the following exception when getting the original size of a network image. This does not make my app crash but would like to handle this. 

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building ImagePixels(dirty, state: _ImagePixelsState#98fea):
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()

The relevant error-causing widget was: 
  ImagePixels file:///C:/Data/Personality/SideProjects/TiengVietDep/tieng_viet_dep/lib/scenes/ReadingPage.dart:146:7
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      double./ (dart:core-patch/double.dart:52:23)
#2      _ReadingPageState.buildContent.<anonymous closure> (package:tieng_viet_dep/scenes/ReadingPage.dart:151:48)
#3      _ImagePixelsState.build (package:image_pixels/src/image_pixels.dart:225:55)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Here is the code to reproduce this exception:

```
Widget buildContent(BuildContext context, String url) {
    final width = MediaQuery.of(context).size.width;
    final height = MediaQuery.of(context).size.height;
    print("Screen size: $width $height");
    Image nimg = Image.network(url);
    precacheImage(nimg.image, context);
    print(nimg);
    return Stack(children: [
      Center(
          child: Image(
            image: nimg.image,
            fit: BoxFit.fill,
            width: width,
            height: height,
          )
      ),
      ImagePixels(
        imageProvider: nimg.image,
        builder: (context, img) {
          return Positioned(
              
              top: img != null ? 92.0 * (height/img.height) : 0.0,
              left: img != null ? 137.0 * (width/img.width) : 0.0,
              child: InkWell(
                onTap: () {
                  print("On tap");
                  playAudio();
                },
                child:
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.grey[100],
                ),

              )
          );
        },
      )
    ]);
  }
```

**Comment by marcglasberg** [comment]
The docs state that:

> If the image is already available, img.hasImage is true, and img.width and img.height indicate the image dimensions.
> While the image is not yet available, img.hasImage is false, and img.width and img.height are null.

So, instead of this:

    top: img != null ? 92.0 * (height/img.height) : 0.0,
    left: img != null ? 137.0 * (width/img.width) : 0.0,

You should have written this:

    top: img.hasImage ? 92.0 * (height / img.height) : 0.0,
    left: img.hasImage ? 137.0 * (width / img.width) : 0.0,

**Comment by cuongpxu** [comment]
Thanks for your response!
