### ISSUE TITLE
[web] Error: Failed to encode the image into bytes.

### ISSUE THREAD

**Issue by IvanDeluxe** [marcglasberg/image_pixels#8]
Hi :)

After upgrading to `flutter 3.0.0` we're unable to use `image_pixels` @ web:
```
Error: Failed to encode the image into bytes.
    at Object.createErrorWithStack (http://localhost:52985/dart_sdk.js:5093:12)
    at Function._throw (http://localhost:52985/dart_sdk.js:20399:18)
    at Function.throwWithStackTrace (http://localhost:52985/dart_sdk.js:20396:18)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52985/dart_sdk.js:40921:18)
    at Object._microtaskLoop (http://localhost:52985/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:52985/dart_sdk.js:40784:13)
    at http://localhost:52985/dart_sdk.js:36261:9
```

We've found [this issue](https://github.com/flutter/flutter/issues/102683) which seems to be the cause of it?

Any help is appreciated.

Thanks,

Ivan

**Comment by marcglasberg** [comment]
I don't use Flutter web, and can't fix this. 

The issue you pointed to could be the problem, so I suggest you wait for it to be fixed and try again. Could you please let me know when you have that info?

**Comment by IvanDeluxe** [comment]
Indeed 🔥

**Comment by Savan7002** [comment]
@marcglasberg Your library supports Web as per pub.dev but here you telling You don't use Flutter web. What a joke.

**Comment by marcglasberg** [comment]
@Savan7002 Flutter web support didn't even exist when this package was created, and pub.dev included this statement about web automatically, without asking me. Joke is me having to respond to entitled people on the internet. Please, be polite. As I do not work for you and this is open source, you can go and fix the problem yourself, and then I'll accept your PR.
